### ISSUE TITLE
pembuatan folder baru 'saves'

### ISSUE THREAD

**Issue by slehmadi** [rizkyramadhana26/TubesDaspro#2]
untuk folder data, karena itu berisi file-file csv. mending buat folder baru bernama 'saves'.
didalam folder 'saves' inilah berisi folder-folder yang nantinya disimpen

**Comment by rizkyramadhana26** [comment]
'saves' ada di dalam 'data' gitu kah ?

**Comment by rizkyramadhana26** [comment]
okeee, ini jawabannya 'data' ada di dalam 'saves'. Folder 'saves' isinya berbagai folder untuk berbagai versi tanggal penyimpanan data
